from sqlalchemy import Column, Integer, String, Text, DateTime, Float, ForeignKey, Boolean
from sqlalchemy.orm import declarative_base, relationship
from datetime import datetime
import os
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker

Base = declarative_base()

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    username = Column(String(50), unique=True, index=True)
    hashed_password = Column(String(100))
    created_at = Column(DateTime, default=datetime.utcnow)
    
    messages = relationship("Message", back_populates="user")
    mood_logs = relationship("MoodLog", back_populates="user")
    recommendations = relationship("Recommendation", back_populates="user")

class Message(Base):
    __tablename__ = "messages"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    sender = Column(String(20)) # "user" or "bot"
    text = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow)
    
    user = relationship("User", back_populates="messages")

class MoodLog(Base):
    __tablename__ = "mood_logs"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"))
    timestamp = Column(DateTime, default=datetime.utcnow)
    depression_score = Column(Float)          # 0.0 to 1.0
    dominant_emotion = Column(String(50))
    classification = Column(String(50))       # "Normal", "Mild", "Moderate", "Severe"
    # ── Extended AI analysis fields ──────────────────────────────────────────
    stress_score = Column(Float, nullable=True)        # 0–100 (higher = more stressed)
    mood_score = Column(Float, nullable=True)           # 0–10 (higher = better mood)
    energy_level = Column(String(20), nullable=True)    # "Low" | "Medium" | "High"
    risk_level = Column(String(20), nullable=True)      # "Low" | "Moderate" | "High" | "Severe"
    confidence = Column(Float, nullable=True)           # 0–100 model confidence %
    sentiment = Column(String(20), nullable=True)       # "Positive" | "Negative" | "Neutral"
    exercise_recommended = Column(String(200), nullable=True)  # exercise title or None

    user = relationship("User", back_populates="mood_logs")


class Recommendation(Base):
    """Tracks every Smart Action Card generated by the AI."""
    __tablename__ = "recommendations"
    id                 = Column(Integer, primary_key=True, index=True)
    user_id            = Column(Integer, ForeignKey("users.id"), index=True)
    recommended_module = Column(String(50))   # "exercise" | "journal" | "assessment" | "mood" | "analytics" | "report"
    recommended_item   = Column(String(200))  # title of exercise, assessment ID, etc.
    recommended_at     = Column(DateTime, default=datetime.utcnow)
    clicked            = Column(Boolean, default=False)
    completed          = Column(Boolean, default=False)
    completion_time    = Column(DateTime, nullable=True)

    user = relationship("User", back_populates="recommendations")

# DB setup
DATABASE_URL = "sqlite:///./chatbot.db"

engine = create_engine(
    DATABASE_URL, connect_args={"check_same_thread": False}
)
SessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)

def init_db():
    Base.metadata.create_all(bind=engine)

def get_db():
    db = SessionLocal()
    try:
        yield db
    finally:
        db.close()
